### ISSUE TITLE
火狐好像不行？

### ISSUE THREAD

**Issue by Lorem3** [lbb00/remove-feishu-watermark#14]

**Comment by lbb00** [comment]
前段时间看了一下，火狐中似乎是 tampermonkey 插件自身报错导致的。暂时没精力研究具体的原因了。

**Comment by lbb00** [comment]
fix #15 

晚上有空看了一下，你在火狐上用的应该是 greasemonkey 这个插件吧。这个插件的 v4 版本不支持 GM_addStyle，兼容了一版，我在 Mac 上测试已经可以了。
