### ISSUE TITLE
Not working since April 2023 | 从2023年4月开始不好使了

### ISSUE THREAD

**Issue by yidingww** [lbb00/remove-feishu-watermark#3]

**Comment by lbb00** [comment]
辛苦告知一下在哪些飞书网页上不可用了，目前在中国的飞书工作台、文档、网页 IM 中仍然是可用的。

**Comment by lbb00** [comment]
之前没有支持海外版的飞书，我更新了一个版本 #4 新增了对 larksuite.com 的支持。但是由于飞书水印只有 pro 用户才可以开启，我无法对移除海外版飞书水印进行测试。也许中国版本与海外版本的代码是一样的，辛苦你更新一下插件，如果是有效果的，请给我一下反馈。

**Comment by yidingww** [comment]
@lbb00 不是海外版域名的问题，看看这个链接：https://bytedance.sg.feishu.cn/docx/JUv6dm4UHo49EMxZghTlnYhHgzc

这个链接是匹配`https://*.feishu.cn/*`的，但是还是有水印

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/28719400/229971598-30ef3c7f-a8d7-44f8-8a41-4649244ea9a3.png">

**Comment by lbb00** [comment]
已经修复 #5。感谢提供信息。比较有意思的是，这个水印仅在 Chrome 并且是 sg.feishu.cn 上出现。hh，我用 Edge 没发现这个问题。
